name: CI
on: pull_request
jobs:
  test:
    name: Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: |
          export NODE_OPTIONS=--max_old_space_size=8192
          npm run lint
      - name: Unit Tests (Polymer CLI)
        run: npm run test:local
      - name: Unit Tests (SauceLabs)
        run: npm run test:sauce
        env:
          SAUCE_ACCESS_KEY:  ${{ secrets.SAUCE_ACCESS_KEY_DESIRE2LEARN }}
          SAUCE_USERNAME: Desire2Learn